server:
  port: 9527
spring:
  application:
    name: cloud-zuul
eureka:
  client:
    service-url:
       defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
  instance:
    instance-id: gateway.com
    prefer-ip-address: true
##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

zuul:
  max:
    host:
      connections: 3000
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

